name: tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  compile:
    name: compiling contracts
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 13.x]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn task:compile
        env:
          CI: false
